name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run cargo fmt
      run: cargo fmt --all -- --check

    - name: Build
      run: cargo build
      env:
          DATABASE_URL: "postgresql://postgres@localhost:5432/demo"

#    - name: Run tests
#      run: cargo test

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
